### ISSUE TITLE
Sekhmet begins levitating off the ground at large sizes

### ISSUE THREAD

**Issue by Raziek** [44madfire/Growing-Rivalry#11]
![image](https://github.com/44madfire/Growing-Rivalry/assets/112226566/4acb55fc-39fc-4c2b-8da6-72361f5c8ae7)
![image](https://github.com/44madfire/Growing-Rivalry/assets/112226566/95efc08d-b338-4d0d-8181-49b456100446)

**Comment by savny004** [comment]
This is just weird. 
Can you write how much Height she had? 
Is it affecting other characters?

**Comment by Raziek** [comment]
> This is just weird. Can you write how much Height she had? Is it affecting other characters?

This starts happening on her final stage art, at around 800+. In this screenshot she is size 1150

![image](https://github.com/44madfire/Growing-Rivalry/assets/112226566/d412d48f-f698-49ea-801a-241c2b754db4)

Issue gets worse as size increases (pictured: 2350)
![image](https://github.com/44madfire/Growing-Rivalry/assets/112226566/ea785963-bfd1-448e-8a8d-582a951938a4)

**Comment by savny004** [comment]
Adjusted the Y value so they start lower. 
Should correct the floating issue.
