### ISSUE TITLE
"Galactic Size Mage" Only counts Galactic cards in exile

### ISSUE THREAD

**Issue by EvanRiley1234** [44madfire/Growing-Rivalry#17]
Had a exile full of around 64 cards (52 were zombie cards or human corpses) when played Galactic size mage only did 12 (the number of galactic cards in exile)

**Comment by savny004** [comment]
Human Corpses do not Exile, they are removed. 
Removed =/= Exile.
Will add text to mention "Galactic" in the ability though.
