### ISSUE TITLE
"Space Force Infantry" when discarded deals 10 damage to player instead of 5 lifesteal damage to opponent

### ISSUE THREAD

**Issue by dark-sider6** [44madfire/Growing-Rivalry#18]
![before](https://github.com/44madfire/Growing-Rivalry/assets/166578884/33e69155-39d3-40d8-a89b-db493e63f1d5)
Using Dark Contract to discard Space Force Infantry.
![after](https://github.com/44madfire/Growing-Rivalry/assets/166578884/e07f2b73-f441-4f4d-be4c-bcd0622a3a2c)

I ended up with a Growth of Victory in my deck, meaning the card effect is Demonic Swordmistress.

**Comment by savny004** [comment]
Corrected the skill location.
