### ISSUE TITLE
Cannot read property "isEnemy of undefined

### ISSUE THREAD

**Issue by Milk-N-Potatoes** [44madfire/Growing-Rivalry#19]
Not sure what caused this one, but I'll give the steps of how I got there

I went to the island and was fighting the first cultist. I fought for a few turns, but the last few I used Zekari then either lambs for slaughter or path of worship, I cannot remember. Then I tried to use succubus queen and got the error. Dominant 2 may not have been active at the time, I didn't think to check before closing.

**Comment by savny004** [comment]
Hopefully this is resolved in v6.03.
If it does happen again, please repost.
