### ISSUE TITLE
Titanic Force & Tyrant Force enemy abilities inflicts wrong effect on player

### ISSUE THREAD

**Issue by Raziek** [44madfire/Growing-Rivalry#21]
Titanic Force inflicts Dominant II, but the player loses height **and** is forced to discard a card.

Based on name, would expect:
Player receives Submissive II, not Dominant II.
Gains an extra card per turn
Loses height per turn
![image](https://github.com/44madfire/Growing-Rivalry/assets/112226566/1310132c-853b-4c51-8953-419c4236406a)

Tyrant Force works similarly, but with Dominant III.

**Comment by savny004** [comment]
Did a test run. 
Enemy gained Dominant. 
Player gains Subservient. (I, II or III) 
So working as it should for now...

**Comment by Raziek** [comment]
This works properly in 6.03 now
