### ISSUE TITLE
Rachel can't be eliminated from the competition

### ISSUE THREAD

**Issue by Raziek** [44madfire/Growing-Rivalry#23]
Even if reduced under elimination threshold, she remains present.

**Comment by savny004** [comment]
Rachel's threshold is less than 100.... unlike the others.
So it takes a while for her actually leave.

**Comment by Raziek** [comment]
Night-time battle, pushed to -300 and defeated with a battle cost of 43
![image](https://github.com/44madfire/Growing-Rivalry/assets/112226566/38b7377a-6db1-4b82-b417-716fd72b7883)

Again somehow rebounded to 124
![image](https://github.com/44madfire/Growing-Rivalry/assets/112226566/9af899af-d1da-4b75-9ef7-1ce652f100bb)

She only has 8 victories to her name

**Comment by savny004** [comment]
Found the issue. She should be able to be eliminated now .
