### ISSUE TITLE
Dominant 1 from "Fairy of Cruelty" is missing status icon and description

### ISSUE THREAD

**Issue by Raziek** [44madfire/Growing-Rivalry#26]
![image](https://github.com/44madfire/Growing-Rivalry/assets/112226566/ae41dec0-d43b-4999-b9f0-9728fba38bf8)

**Comment by Raziek** [comment]
Should also probably be Dominant III, since it lasts for 3 turns, but this is an old card that might need a rebalance, since it was created when Dominance/Submissive effects were temporary

**Comment by savny004** [comment]
Hm. Changed it to Dominant II.

Should inflict Subservient on enemy as well (in theory...)
