### ISSUE TITLE
Stomp deals much more damage that stated in description

### ISSUE THREAD

**Issue by Kostobot51** [44madfire/Growing-Rivalry#31]
Before
![image](https://github.com/44madfire/Growing-Rivalry/assets/166573699/55c7f0ad-0912-44ea-b2e3-51a6bcb30222)
After
![image](https://github.com/44madfire/Growing-Rivalry/assets/166573699/bf4b3c77-49b2-4030-8550-cae362f63b0e)

**Comment by savny004** [comment]
The bracket strikes again!
