### ISSUE TITLE
"Galactic Voidborn" status not functioning properly

### ISSUE THREAD

**Issue by SinSanctum** [44madfire/Growing-Rivalry#33]
Played "Galactic Voidborn" and gained the _Voidborn III_ and _Void Curse_ status.
![image](https://github.com/44madfire/Growing-Rivalry/assets/151354238/8f2033b0-f7c4-419c-82b6-726934838f1b)

Did not gain any **Height** from _Voidborn III_ (should of gained 5*7=35) and only lost 5 **Height** from _Void Curse_ (should of been 7)
![image](https://github.com/44madfire/Growing-Rivalry/assets/151354238/42ecf7e8-8b2d-4ba8-ab1a-173706b27862)

**Comment by savny004** [comment]
Oof. Some missing brackets.
