### ISSUE TITLE
Cursed Existence/Curse Specialist/Curse of Belial Testing Thread/Issues

### ISSUE THREAD

**Issue by Raziek** [44madfire/Growing-Rivalry#35]
**Cursed Existence** - 1st application - Applies Curse of Belial to both sides, both effects read correct. Opponent loses height. Player does not gain height. 

2nd application - Dispels curse from the opponent. Steal effect is still broken (Issue #5). Player gains Curse of Belial when they shouldn't, but it does not award them height. Enemy continues to lose height despite their curse having been consumed/removed.

**Succubus Curse Specialist** - 

1st Application - Both sides gain curse. Functions the same as Cursed Existence's application. (Player does not gain, enemy loses)

2nd application functions as expected but the player's side is refreshed/extended while the enemy's is removed, so they continue to lose height

So there's 2 issues:

1) Player side of Curse is not awarding the player height

2) 2nd use is only dispelling curse from enemy, not player, so it still continues to steal height (and refreshes the duration back to 3 turns)
The damage increase to Belial component appears to be functioning fine

**Comment by Raziek** [comment]
Additional Testing:

Dominant/Submissive effects also override Curse of Belial. If an enemy is afflicted by Dominant 1 (steals 10/turn) and Curse of Belial (Steals 25/turn), they will only lose 10.

**Comment by savny004** [comment]
As per other issue. Gonna have to probably dupe some of the scripts in order for it toregister each iteration. 
Keeping open for now

**Comment by savny004** [comment]
Added a separate script for the Curse of Belial steal. 
Added a clause to remove the "dummy state" from the player.
