### ISSUE TITLE
"Galactic Size Mage" - Stages 2 & 3 not functioning properly

### ISSUE THREAD

**Issue by SinSanctum** [44madfire/Growing-Rivalry#36]
The second growth stage of "Galactic Size Mage" says **VOID:2**, but no cards are voided when played.
The third growth stage of "Galactic Size Mage" says **Steal**, but no is gained when used.

**Comment by Raziek** [comment]
This might be a misinterpretation of the card writing for the stage 3 effect

From when I played it, it does steal, but the Size Mage is the one that gets the +50, not you. It does this because her height is how much damage her final stage does

**Comment by savny004** [comment]
Correct. She's a size mage. She's takes the height. all the height she gets is for her. 
2nd stage was a missed capital letter :( 

Also for 3rd stage 
"Galactic Size Mage" steals 50 Height.

If it was the player, it would just say "Steal 50 Height"
