### ISSUE TITLE
"Fairy Archmage" generated by Fairy Ritual not receiving fairy boost

### ISSUE THREAD

**Issue by Axletowns** [44madfire/Growing-Rivalry#39]
![image](https://github.com/44madfire/Growing-Rivalry/assets/166561533/f77d263b-fdd6-460e-a500-c9ba60ff53f0)

![image](https://github.com/44madfire/Growing-Rivalry/assets/166561533/02a2edeb-4146-42b6-9372-7bd9b009178a)

Fairy Archmage deals 10 damage regardless of how much your fairy damage is boosted.

**Comment by savny004** [comment]
The actual number won't change. It's 10 + the bonus (but i forgot the bonus...)
So added.
