### ISSUE TITLE
Eternal Servitude not applying Sub/Dom correctly

### ISSUE THREAD

**Issue by Obsidian-Dragoon** [44madfire/Growing-Rivalry#40]
It inflicts both status on the Opponent, causing 0 change each turn. I'm not sure which is intended to be inflicted on the user. Based on the wording, it's meant to apply Submissive to the opponent and Dominant to the user. If it's meant to apply Submissive to the user, it should read "Gain Submissive 2".

**Comment by savny004** [comment]
Changed it to gain and changed scope. 
Its meant to give "Submissive" to yourself. 
Enemy gains "Dominant"
Changed mana cost and add a bonus effect so it's not garbage.
