### ISSUE TITLE
Curse of Belial and Dom/Sub not stacking

### ISSUE THREAD

**Issue by Obsidian-Dragoon** [44madfire/Growing-Rivalry#41]
While both Curse of Belial and Dom/Sub are active, only one of the height steal effects will work at the start of your turn. And from what I can tell, it'll prioritize Dom/Sub over Curse of Belial. It should be stealing 25 + whatever the current Sub/Dom rate is.

**Comment by savny004** [comment]
Hmm,. probably cause they use the same "steal" script. so one value overrites the other. 
I'll dupe the event and change it  so they can overlap.
Leaving open till I do

**Comment by savny004** [comment]
Same as earlier. Made Curse of Belial has a separate script. 
Should work as intended now.
