### ISSUE TITLE
Lilith's Battle Victory CG doesn't show up in Gallery

### ISSUE THREAD

**Issue by Obsidian-Dragoon** [44madfire/Growing-Rivalry#42]
The CG that's used when she wins via height drain and is zoomed in on during her victory speech, before the bad end CG is reached (which unlocks just fine).

**Comment by Obsidian-Dragoon** [comment]
![image](https://github.com/44madfire/Growing-Rivalry/assets/166782419/a04fc3af-1b45-4fe4-970a-98c2c7f5888f)
Poorly cropped image for reference.

**Comment by savny004** [comment]
Added some sneaky bits, should hopefully let all of them be added successfully.
