### ISSUE TITLE
6.03 | Luna can go missing from donation list somehow

### ISSUE THREAD

**Issue by Raziek** [44madfire/Growing-Rivalry#47]
![image](https://github.com/44madfire/Growing-Rivalry/assets/112226566/9625fa70-36f7-4169-9a7d-c3c3b4c9d343)
![image](https://github.com/44madfire/Growing-Rivalry/assets/112226566/7b2ccfcc-abf9-4dcf-9ba1-3bf02e429242)
![image](https://github.com/44madfire/Growing-Rivalry/assets/112226566/ac5758aa-fb93-4495-a0b9-3d5598187286)

These photos are all from Day 1 no battles fought. Luna is present and her donation works

The following photos are the list from my day 20 file, Luna is still in the game but has gone missing from the donation list.
![image](https://github.com/44madfire/Growing-Rivalry/assets/112226566/5c126540-a382-4824-a85a-cd8e1a5256d4)
![image](https://github.com/44madfire/Growing-Rivalry/assets/112226566/bc791c35-eef0-4d07-8514-0d6aee4967b2)
![image](https://github.com/44madfire/Growing-Rivalry/assets/112226566/b063793e-ea68-46fe-b49f-4f9a6b5d16b9)
![image](https://github.com/44madfire/Growing-Rivalry/assets/112226566/d7e42a38-103d-49c6-8cd6-0ac722f178ed)

**Comment by savny004** [comment]
Fixed. 
Luna and Victoria were both using incorrect checks.
