### ISSUE TITLE
Cursed Existence does not properly steal height.

### ISSUE THREAD

**Issue by Raziek** [44madfire/Growing-Rivalry#5]
Expected Result: When used on a cursed opponent, the player steals height equal to the number of succubus cards played.

Actual result: The player gains the correct amount of height but the opponent does not lose any.

**Comment by Kostobot51** [comment]
Still happens in 6.03

**Comment by Raziek** [comment]
Closing in favor of https://github.com/44madfire/Growing-Rivalry/issues/35
