### ISSUE TITLE
One of Lucia's arts are very badly stretched

### ISSUE THREAD

**Issue by Raziek** [44madfire/Growing-Rivalry#51]
![image](https://github.com/44madfire/Growing-Rivalry/assets/112226566/84b1c259-b8ba-4a7b-b9a2-dec24d26c6d2)

**Comment by savny004** [comment]
Yeah I know. I'm gonna redo all of hers. I hate them.

**Comment by savny004** [comment]
Added new Lucia art. Hopefully a bit nicer looking.
