### ISSUE TITLE
6.03 | Valeria Demon King's Vengeance applying Voidborn 1

### ISSUE THREAD

**Issue by AfterAllImSoul** [44madfire/Growing-Rivalry#52]
As above, I'm assuming this is meant to do something else.

**Comment by AfterAllImSoul** [comment]
![Screenshot 2024-04-13 101545](https://github.com/44madfire/Growing-Rivalry/assets/166813043/b8fe03a8-6892-4552-901f-49d44f158ccc)

**Comment by savny004** [comment]
Fixed. 
Also fixed a few other statuses behaving oddly with enemies.
