### ISSUE TITLE
Curse of Belial does not cause enemy to lose 25 height per turn

### ISSUE THREAD

**Issue by Raziek** [44madfire/Growing-Rivalry#7]
![image](https://github.com/44madfire/Growing-Rivalry/assets/112226566/6dd4f43c-10e6-429d-a06f-067fecb1aad6)
Description states enemy loses 25 height per turn

**Comment by Kostobot51** [comment]
Still happens in 6.03

**Comment by Raziek** [comment]
For clarity, the enemy loses height, but the player does not gain any, in version 6.03

**Comment by Raziek** [comment]
Closing in favor of https://github.com/44madfire/Growing-Rivalry/issues/35
