### ISSUE TITLE
"Belial, The First" does not gain 10 damage if it kills the opponent.

### ISSUE THREAD

**Issue by Raziek** [44madfire/Growing-Rivalry#8]
If the opponent is cursed and "Belial, The First" reduces the opponent's HP to 0, the "If enemy is cursed, dispel it and "Belial, The First" gains 10 damage" portion of the effect does not trigger.

(Possibly working as intended?)

**Comment by savny004** [comment]
It's sadly the way the trigger works. As damage is always calculated first, if the enemy dies, the rest of the card will not resolve. 
So, yes, technically working as intended.
